### ISSUE TITLE
Mute or Set Level to Channel on Mix Bus

### ISSUE THREAD

**Issue by BibraDesign** [bitfocus/companion-module-behringer-x32#11]
Would it be possible to being able to mute a channel or set its level on a mix bus, not only on the Main LR as it is now? That would be so helpful, as we try to create an intercom-solution using a X32 and a couple of Streamdecks. Thanks so much.

And of course, if toogle / feedback of mute would somehow work it would make such a difference.

**Comment by BibraDesign** [comment]
I´ve just discovered that the xair-module has that feature. So it should be possible, as the xair and 
x32 are somewhat similar?

<img width="672" alt="Bildschirmfoto 2020-03-10 um 10 55 47" src="https://user-images.githubusercontent.com/8734632/76301002-e2b3da00-62bd-11ea-8b9e-8ec78ca43d80.png">

**Comment by Brennan-Dan** [comment]
Is there any update on this being implemented for X32? This would be a really useful feature to have.

**Comment by Julusian** [comment]
Mutes for channel/aux/fx-return to bus/main is implemented in latest v2 builds.
I am working on the levels, waiting on having the time to finish

**Comment by BibraDesign** [comment]
Wow this is great, thanks so much already!

**Comment by Brennan-Dan** [comment]
> Mutes for channel/aux/fx-return to bus/main is implemented in latest v2 builds.
> I am working on the levels, waiting on having the time to finish

That sound really good! will take a look later today. 

I was working on bits of code just to control the channels within the bus if you want to take a look and can probably be modified to do the same for any other channel banks? I had the functionality working for turning each channel on and off and adjusting the levels within a bus tested and working locally. I'm completely new to this so just finding my ways of using GitHub, javascript etc. https://github.com/Brennan-Dan/companion-module-behringer-x32

**Comment by Brennan-Dan** [comment]
Is there any update when the Level Adjustment for each channel within the bus will be implemented into the X32 Module? Many thanks. Dan.

**Comment by Julusian** [comment]
@Brennan-Dan you gave me the kick I needed to get this finally done :)
This is implemented now, along with the same properties for bus to matrix sends

**Comment by Brennan-Dan** [comment]
That's great news!! thanks for your help in getting this functionality added! It looks like there is a bug with the latest upload with the module not being able to be found. I look forward to using the feature though! Thanks.
