### ISSUE TITLE
Solicitud de función aumenta fader y disminuir fade y mute on/off

### ISSUE THREAD

**Issue by audiovisualfj** [bitfocus/companion-module-behringer-x32#118]
Buenas, al hacer la configuración de la midas, veo que que tiene Adjust fader level pero lo hace solo en un canal especifico ya configurado en el Target. Lo que quiero sería poder utilizar un botón en companinion con midas:Select que lo tiene, y que cuando este este selecionado en el canal que quiero solo hacer un boton de Adjust fader level pero controlando el que este seleccionado. Al igual q con el mute poderlo poner en ON/OFF el que este seleccionado. 
La idea es tener 5 botones de 5 mic, los cuales pueda seleccionar, al tenerlo seleccionado poder subir y bajar fade (canal seleccionado) y poderlo poner el mute en on/off (el canal seleccionado).
Adjunto imagen: Captura 1 es como lo tengo configurado cada canal tiene su mute arriba y su fader abajo.
                            Captura 2 es como querría configuralo.

Muchas gracias
![Captura 1](https://github.com/bitfocus/companion-module-behringer-x32/assets/166597767/a7695306-31ed-4dcf-b4de-2a832de39c83)
![Captura 2](https://github.com/bitfocus/companion-module-behringer-x32/assets/166597767/02a83490-195f-4ca3-8bd9-897cf4e38dae)

**Comment by piedrola** [comment]
Me parece que el autor ya no está trabajando con el repositorio. Tengo un consejo: usa el plugin general de OSC para lograr lo que estás imaginando. Puedes utilizar variables personalizadas: selecciona un botón de un micrófono y guarda la selección en una variable personalizada. Con OSC, puedes llamar a la selección al botón de mute, por ejemplo. Subir y bajar los faders es un poco complicado, pero es posible. Te puedo enviar mi configuración y puedes aprender del ejemplo. 

Saludos
Dani

**Comment by audiovisualfj** [comment]
muchas gracias por la respuesta, no se muy bien como hacerlo con el OSC, si me pasa configuracion te lo agradecería, la idea es tener en una capa mas botones de seleccion y solo 1 de mute y dos de subida y bajada de fader es que sino tengo q hacerlos en varias paginas y es más coñazo, te paso mi correo (audiovisual.fj@gmail.com) por si me quieres mandar la configuracion y asi veo el ejemplo, muchas gracias

**Comment by audiovisualfj** [comment]
@piedrola Hola Dani, te agradecería si me puedes mandar el ejemplo ya que no consigo hacer la variable personalizada, gracias
