### ISSUE TITLE
BUG: "Select" Action Not Working on M32R

### ISSUE THREAD

**Issue by ukiews** [bitfocus/companion-module-behringer-x32#130]
As the title states, using the "Select" action does not select the corresponding channel on my M32R.

**Comment by CobbleShop** [comment]
I'm not sure but i don't think you can "select" a channel, but rather a group of active channels, depending on your console. 1-16, 17-32 (....)

**Comment by jwetzell** [comment]
Definitely can select a channel on the X/M32. I tested this on an X32 Rack and works as expected. I can get an M32R set up and test the same method with that and see if there is any difference.

**Comment by ukiews** [comment]
Looks like does work. It was not updating the Mac app selection.
