### ISSUE TITLE
X32 Core Stuck in Synchronizing State

### ISSUE THREAD

**Issue by mrlad** [bitfocus/companion-module-behringer-x32#15]
The X32 module works fine, but the module status is permanently syncing and remains yellow.

**Comment by mrlad** [comment]
Today, none of the devices/buttons were active in Companion after it was running for a week or so.  I killed it and restarted it and the X32 module connected and its now in green state

**Comment by Julusian** [comment]
I don't know how to progress on this.. With it now working it sounds like a one off issue, so unless it can be reproduced I dont know what can be done

**Comment by mrlad** [comment]
The only reproduction scenario could you try is to do a fresh install of companion 2.0 (after upgrading from 1.x).  Then install modules in this order

1. ATEM
2. Videohub
3. Hyperdeck (disabled)
4. x32
5. ProPresenter

If you can't replicate it with those steps, probably should close it out as unreproducible @Julusian .

**Comment by Julusian** [comment]
I had this happen the other day. A simple disable & enable of the module resolved it.
I think it might have been when the x32 as powered off when companion started. I shall do some digging

**Comment by Julusian** [comment]
I have pushed a fix for this.
The connection was getting stuck syncing if the x32 did not respond to the initial `/xinfo` command we send, and would also not detect it going offline which could cause a state mismatch when it became available again
