### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Tanis74** [bitfocus/companion-module-behringer-x32#17]
New install of Companion( companion-2.0.0-a0c79fa-2397) send to log
`module(behringer-x32): Error loading module: Error: Cannot find module 'C:\Program Files\Companion\resources\app.asar/lib/module/behringer-x32/dist/index.js'`

**Comment by Brennan-Dan** [comment]
I'm having the same issue after the latest module update.

**Comment by Julusian** [comment]
A fixed version is building now
