### ISSUE TITLE
"Syncing" communications error build 2334

### ISSUE THREAD

**Issue by shaunus** [bitfocus/companion-module-behringer-x32#19]
Running stable on build 2330 but after updating to build 2334, module will not connect to X32. Status changes to "Syncing" and will not resolve. I posted in the Facebook group, here's a link to that discussion:

https://www.facebook.com/photo.php?fbid=10157423562378133&set=gm.2617979345087066

I've tried changing IP, editing/applying changes, disabling/enabling, etc., nothing I did resolved. I tried creating a completely new/blank version (by removing DB file), adding new instance, still no joy.

I tested more recent builds including 2443 to no avail. It seems clear that this bug was introduced in the major rewrite of 2334.

I'm happy to help however I can, but for right now, I'm stuck on build 2330! I've been able to forward test and roll back to 2330 each time with no problems.

**Comment by Julusian** [comment]
I shall dig into this more soon. What firmware version are you on? 

One more thing I should add, is that while it is stuck syncing, it should be no less functional than in build 2330 or earlier.
Being stuck syncing means that it is trying to receive the initial state for feedback and variables (which was added in 2334), but actions should still be fine.

**Comment by shaunus** [comment]
Thanks for digging in. Oh that's good to know about the actions still being operational, I'll be sure to test it out in the next day or so. I thought because the orange square/stop icon appeared on each button with an associated action, it meant it wasn't communicating.

Hmm I think firmware version 2.0?
Product ID:	0x006c
  Vendor ID:	0x0fd9  (Elgato Systems GmbH)
  Version:	2.00

**Comment by Julusian** [comment]
For most modules the orange square/stop icon does mean that, but due to the x32 protocol it should still work.

Sorry, I meant the firmware on your x32. Mine is on 4.02, so I am wondering if it is something it doesnt like with older firmwares

**Comment by shaunus** [comment]
oh got it, sorry I should have intuited that haha -- when I bring up the info page on X32 iPad software, it says under the IP addressed "Info -- X32RACK 2.14" but then at the bottom it says version 3.1.0 build 3.1.0.1 -- so I guess firmware on X32 is 2.14 and the iPad software is 3.1.0! Sounds like I need to update, will probably be tomorrow before I can do that.

**Comment by shaunus** [comment]
It looks like firmware update to the X32 has done the trick! Thanks a bunch. I'll close this ticket and update my Facebook post also.
