### ISSUE TITLE
Add a Slow fade

### ISSUE THREAD

**Issue by MarauderSeeker** [bitfocus/companion-module-behringer-x32#21]
It would be nice to have a fade option so we could fade from -90 to -5db, and take x seconds to do so. Right now to do this I've had to create like 20 set fader options to gradually raise or lower the volume of a channel, for a transition

**Comment by Julusian** [comment]
Yeah I like this idea. I shall take a stab at it when I have some time, and do #16 at the same time

**Comment by Julusian** [comment]
This is now implemented
