### ISSUE TITLE
Controlling Behringer X32 with new update[BUG]

### ISSUE THREAD

**Issue by PCSprod** [bitfocus/companion-module-behringer-x32#22]
I am not able to mute channels anymore using companion/stream deck. Is this due to the new update or does anyone else have this issue? 

Normally I can set a button on the stream deck to mute a certain channel and it no longer works. I get a java pop up error as well.

**Comment by Julusian** [comment]
Can you provide a screenshot of the error dialog?
It should work, I use the latest version daily without issue.
Also could you check what firmware is running on your x32

**Comment by Julusian** [comment]
I am closing this as there is not enough information to work from
