### ISSUE TITLE
Return Fader Level to previous state after a button is deactivated/completed its action. 

### ISSUE THREAD

**Issue by Brennan-Dan** [bitfocus/companion-module-behringer-x32#26]
An option to return a fader level to a previous set level after a button has been pressed. for example, if you set a level of a channel but then had a toggle button that set it the fader to -90db while that button is in operation but after it is depressed it returned to its previous state/level.

**Comment by Brennan-Dan** [comment]
@Julusian Is this something you are able to look at at all?

**Comment by Julusian** [comment]
This is now implemented.
It should be setup like this (there are a couple of presets to help):
![image](https://user-images.githubusercontent.com/1327476/93389726-74e7fc80-f864-11ea-9c0c-423be16f2f68.png)
Internally, it tracks values per button, and can track multiple faders per button too (hopefully that makes sense). I am open to changing that to be a shared value across all buttons (ie, button 1 does the store, and button 2 can recall) if you think that would be better?

**Comment by Brennan-Dan** [comment]
Hi Julusian, 

Thanks for the work on the above, it does work really well. I think the only thing I would like to add if possible is to have a default "store value". So If no level is stored, set to (set value) “0db”. and if it is adjusted after that point then store the new value. 

I hope that makes sense. 

Dan

**Comment by istnv** [comment]
@Brennan-Dan 
I have been adding this feature to the XAir module and thought about this. An operator may be quite startled to have a channel go from -90dB to 0dB because it had not been previously stored. Same situation if the default was -90dB. I think it is safer to ignore an empty recall than to assume a certain level.
John
> Hi Julusian,
> 
> Thanks for the work on the above, it does work really well. I think the only thing I would like to add if possible is to have a default "store value". So If no level is stored, set to (set value) “0db”. and if it is adjusted after that point then store the new value.
> 
> I hope that makes sense.
> 
> Dan

**Comment by Brennan-Dan** [comment]
> This is now implemented.
> It should be setup like this (there are a couple of presets to help):
> ![image](https://user-images.githubusercontent.com/1327476/93389726-74e7fc80-f864-11ea-9c0c-423be16f2f68.png)
> Internally, it tracks values per button, and can track multiple faders per button too (hopefully that makes sense). I am open to changing that to be a shared value across all buttons (ie, button 1 does the store, and button 2 can recall) if you think that would be better?

I think after doing some mapping and use cases being able to share the value across all buttons would be a huge benefit, If that's something that can be implemented.

**Comment by Brennan-Dan** [comment]
> This is now implemented. It should be setup like this (there are a couple of presets to help): ![image](https://user-images.githubusercontent.com/1327476/93389726-74e7fc80-f864-11ea-9c0c-423be16f2f68.png) Internally, it tracks values per button, and can track multiple faders per button too (hopefully that makes sense). I am open to changing that to be a shared value across all buttons (ie, button 1 does the store, and button 2 can recall) if you think that would be better?

Hi @Julusian after playing around with this feature for a few weeks, I was wondering if there is a way of it being a shared value. I'm currently weighing up the advantages/disadvantages of this. would there be a way of choosing between a shared value or not?
