### ISSUE TITLE
Testing with X32 emulator

### ISSUE THREAD

**Issue by stevereids** [bitfocus/companion-module-behringer-x32#27]
I was hoping to use the X32 emulator (https://sites.google.com/site/patrickmaillot/x32#h.p_rE4IH0Luimc0) whilst testing some configurations, but the companion driver never connects properly.  The status remains 'Connecting'. Some commands do appear to be sent, but the device is flagged as unresponsive?  The emulator seems to respond correctly to my other X32 clients.

**Comment by Julusian** [comment]
I have identified a bug which caused this module to fail to reconnect after the config was changed, that is likely the issue you are seeing here as it got stuck at connecting.
Could you update to the latest beta and give it another test?

**Comment by Julusian** [comment]
assumed fixed
