### ISSUE TITLE
[BUG] x32: Set mute - Toggle option does not work as expected, ie toggle

### ISSUE THREAD

**Issue by BlakesHeaven** [bitfocus/companion-module-behringer-x32#29]
Hello, Thanks for this module for Companion!
Firstly, I have what I believe is currently the latest version of Companion installed
![image](https://user-images.githubusercontent.com/37149377/93461935-625dd980-f8dd-11ea-9665-2b6f7f0ebe26.png)

Last night I added the x32 Behringer/Midas, configured the IP address and am happy to confirm it has connected successfully despite the status reporting "null", however, that is off-topic...
 
![image](https://user-images.githubusercontent.com/37149377/93462144-c1235300-f8dd-11ea-982d-e24ffa43d86c.png)

I added a 'Set Mute' action to "Mute" Channel 17 and on pressing the StreamDeck button the Desk's Channel light duly came on. 

I changed the 'Set Mute' action to "Unmute" Channel 17 and again it worked, i.e. the light went off.

So far so good...

**Issue**
I changed the  'Set Mute' action to "Toggle" Channel 17... my expectation was that on pressing the button it would Mute if it was unmuted and visa-versa - unfortunately it does not work.  It may work once if you get it going the right way the first time (sorry not too sure), however, it certainly does not do anything thereafter.

**Expected behaviour**
From a single action, the option '"Toggle" should

- change the status from Mute to Unmute if already muted, 
- change the status from Unmute to Mute if currently unmuted

Workaround - have two actions and 'Latch/Toggle' ticked as shown below:
![image](https://user-images.githubusercontent.com/37149377/93463312-7c002080-f8df-11ea-89ae-674ea8b42843.png)

BTW - I'll raise a separate issue regarding the 'Change colors from mute state' as that does not seem to work.

**Comment by Julusian** [comment]
It sounds like your companion isnt truely connected.
This module is a bit 'quirky' in that regard, where you can send commands even when the status does not report connected.
But as neither toggle or the feedbacks are working, it suggests it isnt receiving anything back.

So the problem here looks to be the 'null' status that it is reporting.
Could you try restarting companion, to see if that changes it?
Also, what x32 firmware are you running?

**Comment by BlakesHeaven** [comment]
Many thanks for the quick responce. 

The X32 is not for me to change or upgrade, but I am just told we are on v3.11.
The person who would update it says he is aware of 4.xxx, but as it looks quite difference, he is holding off upgrading.

I will have to get back to you on the restart of companion as the sound desk is off and I won't be on site until tomorrow or Saturday.

It makes sence what you say if info is not getting back to the PC and i can see why that would impact both the toggle and colour change.

BTW - I like your use of the technical term, "quirky" - very good.

**Comment by Julusian** [comment]
Have you managed to have a look into this at all?

If you cant get it working I shall look at downgrading my x32 firmware for a day to see what I can find

**Comment by BlakesHeaven** [comment]
Hi, thank you for coming back; sorry for leaving it a bit.
I did have another go and it is the same story. I powered up the PC from off, with the desk already on and the two connected via USB. The status in Companion now shows connecting,  and remains as such. Everything else remains as before; I can send to the desk to mute a channel and unmute it with seperate actions, but no apparent feed back to use the toggle option or change button colour.
Thanks!

**Comment by Julusian** [comment]
This is very strange, I have just tried 3.12 myself and it happily connected.
What OS are you using? I can throw together a build that produces a very verbose log which should help identify where it is getting stuck.

**Comment by BlakesHeaven** [comment]
Thank you very much @Julusian, for your diligence and support on this - it is much appreciated.
We have Windows 10 
![image](https://user-images.githubusercontent.com/37149377/94341287-f166a200-ffff-11ea-8904-8c965186ed37.png)
I have just been up to church this morning and it remains the same.

For additional info, the USB cable is primarily used to transmit audio between the x32 and the PC. The PC hosts vMix, Companion and does the streaming to YouTube. The Desk audio (for mics and band) comes into the PC via USB through the Behringer audion driver. For any videos running on the PC the audion goes out via the USB cable using Bus A.

Clearly we can transmit between the two and Companion goes one way; might there be a setting in the x32 that needs adjusting? If there are any logs I can upload please advise how/where I find them.
Thanks again...

**Comment by Julusian** [comment]
Sorry for the delay here, could you give the latest beta build a try?
I found some issues with state handling around connection that could have been your problem here.

**Comment by discodancepant** [comment]
@Julusian This is fixed, the issue can be closed.
