### ISSUE TITLE
M32 Set Fader Level Toggle  ssue

### ISSUE THREAD

**Issue by KDLN** [bitfocus/companion-module-behringer-x32#3]
When having a toggle to set two different levels on a fader it does not change the level. 

Example would be 

Set CH15 +5 on toggle Set CH15 -6 off toggle it stays on +5 on every press. 

When separated out to their own button it works just fine.

**Comment by PerRoine** [comment]
Please describe what you are doing as i have tested this and it works perfectly, there is currently no way to release do this i a relative way as we do not read any values from the x32

**Comment by KDLN** [comment]
I have it set to toggle,
“On” is +5db for channel 15 “off” is -6db for channel 15. When I press it it only goes to +5db I have removed button and started over a few times. When they are two separate buttons it works just fine.


________________________________

**Comment by PerRoine** [comment]
Are You using the up action for the off or are both in the down action VOX ?

**Comment by PerRoine** [comment]
Box not VOX

**Comment by KDLN** [comment]
They are on the separate action, on/off down/up if that is what you are asking.

One is no yellow bar other is yellow bar on top of the button.


________________________________

**Comment by Julusian** [comment]
In recent versions of this module this does work as intended, so this has likely been fixed since this was opened.
If this is still a problem in latest 2.0 please reopen
