### ISSUE TITLE
[BUG] x32: Change colors from mute state does not seem to work.

### ISSUE THREAD

**Issue by BlakesHeaven** [bitfocus/companion-module-behringer-x32#30]
Hello,
I have what I believe is currently the latest version of Companion installed
![image](https://user-images.githubusercontent.com/37149377/93464133-9686c980-f8e0-11ea-9549-4507983678ff.png)

Following on from #29 (Set mute - Toggle option does not work), I also found that the 'Change colors from mute state' does not seem to work. 
![image](https://user-images.githubusercontent.com/37149377/93464064-80790900-f8e0-11ea-878d-a727261d6609.png)
I would probably expect the last one above, setting the colour to red to be the only one necessary, ie it would change to the default colour when not true.
I then went on to trying two explicit feedback colour changes and again no joy.

Fortunately, I can just see the sound desk and the mute button, albeit a bit of a stretch. This, of course, is all the more important when the sound desk is not visible.

Thanks for your consideration on this and what is a great product.

**Comment by discodancepant** [comment]
> Hello, I have what I believe is currently the latest version of Companion installed ![image](https://user-images.githubusercontent.com/37149377/93464133-9686c980-f8e0-11ea-9549-4507983678ff.png)
> 
> Following on from #29 (Set mute - Toggle option does not work), I also found that the 'Change colors from mute state' does not seem to work. ![image](https://user-images.githubusercontent.com/37149377/93464064-80790900-f8e0-11ea-878d-a727261d6609.png) I would probably expect the last one above, setting the colour to red to be the only one necessary, ie it would change to the default colour when not true. I then went on to trying two explicit feedback colour changes and again no joy.
> 
> Fortunately, I can just see the sound desk and the mute button, albeit a bit of a stretch. This, of course, is all the more important when the sound desk is not visible.
> 
> Thanks for your consideration on this and what is a great product.

This is fixed. I use feedback to change buttons on channel mute state and channel to mixbus mute state.
