### ISSUE TITLE
Setting required on the X32 to enable Companion to connect

### ISSUE THREAD

**Issue by EliotWalker** [bitfocus/companion-module-behringer-x32#35]
Hi,
I have the X32 Producer with V4.03 firmware with a factory reset on the settings connected with a static IP address using a wired connection to a Mac. I can control the desk and watch changes on the desk on the Mac using the X32 edit software on the Mac (via the network cable, no USB cable connected) so I am sure that I have bi-directional control available. Companion is running and I have added the X32 instance however it just stays in the "connecting" state. Do I need to enable anything on the desk to allow control from Companion? 

I have a Blackmagic ATEM mixer connected to the same network which I am able to control along with the OBS instance which I am also able to control without any issue.

**Comment by PhilKloppers** [comment]
I am experiencing the same issue - cannot get an instance to connect to my X32 with 4.03 firmware. I didn't try with the previous 4.02 firmware. This is on both Mac and windows 10 installs of Companion.

**Comment by tenacioustechie** [comment]
I'm having this problem as well with the Midas M32, it doesn't seem to be get connected. I'm not sure what other info I can provide (I'll collect the firmware version when I'm next there in the next couple of days, but I think we are on the latest 4.03 or version before that).

**Comment by knelsonkc** [comment]
Same issues. Same firmware (4.03) Companion just says "connecting." I didn't try it with the previous firmware.

**Comment by Julusian** [comment]
I suspect this is a bug where it wont connect after updating the device config, but it should then work after a restart of companion. If not then I dont have any ideas as to the cause for now

**Comment by knelsonkc** [comment]
> I suspect this is a bug where it wont connect after updating the device config, but it should then work after a restart of companion. If not then I don't have any ideas as to the cause for now

I couldn't resolve the issue with a restart of companion and the x32. BUT, it does work with the beta of Companion (Build: companion-2.1.1-140fd7c-2661) I suspect it will be fine the next release.

**Comment by Julusian** [comment]
Companion 2.1.1 is now released. Please give it a try and let me know how it goes

**Comment by PhilKloppers** [comment]
> Companion 2.1.1 is now released. Please give it a try and let me know how it goes

Connected without issue and all functions working so far. X32 on 4.03, Companion 2.11 on Win10
