### ISSUE TITLE
Yarn build command fails in WSL 2 because of 'trash' command

### ISSUE THREAD

**Issue by hjoelr** [bitfocus/companion-module-behringer-x32#36]
https://github.com/bitfocus/companion-module-behringer-x32/blob/47d6667c09481ec38319319860ab98bd983d0eda/package.json#L18

I'm using WSL 2 as my Linux environment and the `trash dist` part of the build command keeps failing.

![image](https://user-images.githubusercontent.com/221971/97515289-23ed1d00-1967-11eb-9710-b41dfdbc90b1.png)

I was wondering if it would be okay to change the build command to the following?

```bash
"build": "rm -r dist && yarn build:main"
```

This would work more universally.

**Comment by JeffreyDavidsz** [comment]
Could you create a pull request for that? Seems like a good suggestion, but this way we can track and review better

**Comment by Julusian** [comment]
I wouldn't go with `rm -r` because for anyone running on windows not via wsl that will fail. I would try using rimraf or some other npm package to do the delete

**Comment by hjoelr** [comment]
@JeffreyDavidsz @Julusian Okay, I didn't realize the `trash` command was most likely using the [NPM trash utility](https://www.npmjs.com/package/trash). I was wondering how it even did anything as I didn't have a native trash command in WSL 2.

To be fair, this isn't really a bug with this (and a few other Companion) plugins. It really appears to be a bug in the NPM `trash` utility and/or Docker (which I used for other projects). @Julusian, good point about being cross-platform. Substituting `trash` for `rimraf` seems to work in WSL 2. I can submit a PR for this.

**Comment by Julusian** [comment]
Im not sure its worth the effort for you to create a pr. I think there is ~5 modules which will need updating then merging into companion, so itll be quicker for me to do it for them all at once.
Ill try and do that this evening, but I might not get to it

**Comment by hjoelr** [comment]
That would be great! Thank you. I've currently worked around the issue in my dev environment by preemptively deleting the `dist` folders before calling the `update.sh` utility. However, not having to do that step would be great too :).

**Comment by Julusian** [comment]
@hjoelr I have gone through and replaced trash with rimraf in all of the modules that were using it. Hopefully this works for you now :)

**Comment by hjoelr** [comment]
@Julusian Thank you!
