### ISSUE TITLE
Fader Flip (Sends on Fader)

### ISSUE THREAD

**Issue by rockinski** [bitfocus/companion-module-behringer-x32#39]
I'd love an action to activate "fader flip". I'd program a button to execute the action "fader flip" and "select bus" so I could so directly into fader flip (e.g. sends on fader) mode with a dedicated bus selected.

**Comment by justingiffard** [comment]
won't lie I didn't understand this at all until I watch an M32 video, X32 doesn't have "fader flip" label only "sends on fader".
Will look into this, but will need to test on our X32 at church

**Comment by Julusian** [comment]
Available in the latest beta
