### ISSUE TITLE
Feature Request: start/stop X32 USB recording

### ISSUE THREAD

**Issue by tigert10** [bitfocus/companion-module-behringer-x32#42]
Hi, for my situation it would be very helpful to have a function to start/stop the usb audio recording on an X32 compact thru bitfocus/streamdeck. I don't know if this is possible but it would be greatly appreciated if someone could implement this functionality.
Thanks!

**Comment by Julusian** [comment]
To make it easier, please share a screenshot from x32edit highlighting the controls/buttons/whatever that do this

**Comment by tigert10** [comment]
> To make it easier, please share a screenshot from x32edit highlighting the controls/buttons/whatever that do this

Sure! The controls only show up when a console is connected (I'm assuming because not all X32 models have a USB recording option???) However, the model I am using is the X32 Compact and when it is connected to x32 Edit Software the recording section appears as shown in the first image, when you click on the record button then a different window appears as in the second images. I'd love to be able to have an option in Bitfocus Companion to assign a button on the Streamdeck to start/stop the USB recording.  Thanks!
![1](https://user-images.githubusercontent.com/35713796/114579177-d6c1e680-9c3a-11eb-931e-adad2176461c.PNG)
![2](https://user-images.githubusercontent.com/35713796/114579191-da556d80-9c3a-11eb-8661-db7c28b13bd1.PNG)

**Comment by istnv** [comment]
Those are part of the 'Tape Operation' action

**Comment by istnv** [comment]
![image](https://user-images.githubusercontent.com/51003420/114588471-931bac80-9c3b-11eb-9aee-cebc24531271.png)

**Comment by tigert10** [comment]
Right on! Don't know how I missed that. You're the best, thanks!
