### ISSUE TITLE
Feature Request: Tape Operation Feedback & Variable

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-behringer-x32#43]
Would it be possible to get feedback and variables on the various states of Tape Operation?

**Comment by justingiffard** [comment]
I'm looking into this. Have feedback working but struggling with the variable for the elapsed time (for record and playback)

**Comment by justingiffard** [comment]
Think I have this figured out, going to try test either tonight or Sunday morning before PRing 😄 stand by 😉

**Comment by justingiffard** [comment]
We we have a build 😃 It's in beta build: companion-2.2.0+3850

https://bitfocus.io/companion/download/builds/

<img width="657" alt="Screenshot 2022-02-03 at 23 05 51" src="https://user-images.githubusercontent.com/3730862/152428798-3ae4f050-1f56-4105-b331-94448ad64f36.png">
