### ISSUE TITLE
New Variable: Fader Level of Channel Send

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-behringer-x32#44]
Would it be possible to have variables for the fader levels of a channel send.

I am aware that this could run into a lot of variables, but it would be useful to be able to show them, so that we can control the mix into buses.

Our usecase - we use a mixbus to control our stream mix, while FOH is done off the standard channels - it would be good to be able to manage/control levels into the stream mixbus from companion as it's controlled from a separate area.

**Comment by justingiffard** [comment]
Its possible yes, but It ~864 variables to add which is an insane amount of variables to add (32 inputs x 16 busses + 8 aux x 16 busses + 8 FX RTN x 16 buses + 16 buses x 6 matrices)

Do you really need to see the level that the sends are at on the companion to control them on the mix buses?

Maybe one possible way of dealing with this is have a bus specified in the config for the instance and then only have variables going to that bus 🤔 even so though its not exactly a pretty solution

**Comment by jmcc94** [comment]
Totally understand the total amount of variables that this could introduce...

I was going to use the variable to show the level as part of the button text, and would really only use this for the sends to a stereo bus.... so we can control the livestream bus from a separate location. 

A choice of a bus in the config could work... Just thinking another thought - could this be achieved by Feedback.... but I suspect not...

Maybe I just use X32 Edit to control the levels....

**Comment by justingiffard** [comment]
You can use feedbacks by setting text based on the levels but that would be
a mission to set up

I can add the channels to a selected mix bus if you like but honestly what
I would (and do use) is Mixing Station on a cheap Android tablet (iPad
would work too but Android is cheaper)

X32 Edit would work too though

Do you want me to try to add a variable set for one bus?

**Comment by jmcc94** [comment]
Thanks for the offer, but no, I don't think it's worth it at this stage.

 I'll close the issue.
