### ISSUE TITLE
Feature Request: Monitor Output Set Level / Dim

### ISSUE THREAD

**Issue by JeffInHighDef** [bitfocus/companion-module-behringer-x32#49]
Thanks for a great frame work. I would like to propose a monitor output level control. Either a Set Volume or DIM amount. This helps in vmix when playing a video, the sound can come into the control room. When it is back live, the triggers can dim down the room levels.

Thanks.

**Comment by justingiffard** [comment]
Looking into it, will need to test on our X32 at church though

**Comment by Julusian** [comment]
Available in the latest beta
