### ISSUE TITLE
Module wont run in Companion 2.2.0-0d9110af-3609

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-behringer-x32#52]
In the latest build of Companion 2.2.0-0d9110af-3609 I get the following error codes when trying to start the X32 module

21.11.15 11:59:31 instance(oGjKKKyCX): Instance failed to launch: mod is not a constructor
21.11.15 11:59:31 module(behringer-x32): Error loading module: Error: Cannot find module 'C:\Program Files\Companion\resources\app.asar/node_modules/companion-module-behringer-x32/dist/index.js' Require stack: - C:\Program Files\Companion\resources\app.asar\lib\instance.js - C:\Program Files\Companion\resources\app.asar\app.js - C:\Program Files\Companion\resources\app.asar\electron.js -
21.11.15 11:53:29 module(behringer-x32): Error loading module: Error: Cannot find module 'C:\Program Files\Companion\resources\app.asar/node_modules/companion-module-behringer-x32/dist/index.js' Require stack: - C:\Program Files\Companion\resources\app.asar\lib\instance.js - C:\Program Files\Companion\resources\app.asar\app.js - C:\Program Files\Companion\resources\app.asar\electron.js

**Comment by Julusian** [comment]
This shouldnt happen anymore
