### ISSUE TITLE
Master not building

### ISSUE THREAD

**Issue by justingiffard** [bitfocus/companion-module-behringer-x32#54]
Hi @Julusian, I see that master isn't building and the issue is line 64-66 and 78-80 of index.ts. Seems that maxWait, before and after don't exist in the Option type? This change was made in commit ff3ecf4 where you made the commit 'revert "bugfix"' please can you look into this? 

I have commented it out for the time being so I can build and it succeeds but don't want to step on toes by reverting the commit you made to revert commit e685d4d. I won't push those changes

**Comment by Julusian** [comment]
ok, this is strange, I promise you it does build with those lines in there
the companion betas are using a version with those lines in without issue, and I can happily build it on both mac and linux.

what os are you on?

**Comment by justingiffard** [comment]
Really? That's very strange. I'm currently on my laptop running Windows. I can switch to my Ubuntu install or to my Macbook but its very weird that it refuses to build. 

Here is the errors I get when I try build with those lines (I build with `yarn build` so nothing special):

```
yarn run v1.22.17
$ npx rimraf dist && npx typescript@~4.2 -p tsconfig.build.json
npx: installed 12 in 1.729s
npx: installed 1 in 2.048s
src/index.ts:64:4 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(input: () => void, options: ImmediateOptions): DebouncedFunction<[], void>', gave the following error.
    Argument of type '{ wait: number; maxWait: number; before: boolean; after: boolean; }' is not assignable to parameter of type 'ImmediateOptions'.
      Object literal may only specify known properties, and 'maxWait' does not exist in type 'ImmediateOptions'.
  Overload 2 of 2, '(input: () => void, options?: Options | undefined): DebouncedFunction<[], void | undefined>', gave the following error.
    Argument of type '{ wait: number; maxWait: number; before: boolean; after: boolean; }' is not assignable to parameter of type 'Options'.
      Object literal may only specify known properties, and 'maxWait' does not exist in type 'Options'.

64    maxWait: 500,
      ~~~~~~~~~~~~


src/index.ts:78:5 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(input: () => void, options: ImmediateOptions): DebouncedFunction<[], void>', gave the following error.
    Argument of type '{ wait: number; maxWait: number; before: boolean; after: boolean; }' is not assignable to parameter of type 'ImmediateOptions'.
      Object literal may only specify known properties, and 'maxWait' does not exist in type 'ImmediateOptions'.
  Overload 2 of 2, '(input: () => void, options?: Options | undefined): DebouncedFunction<[], void | undefined>', gave the following error.
    Argument of type '{ wait: number; maxWait: number; before: boolean; after: boolean; }' is not assignable to parameter of type 'Options'.
      Object literal may only specify known properties, and 'maxWait' does not exist in type 'Options'.

78     maxWait: 500,
       ~~~~~~~~~~~~



Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Julusian** [comment]
Ive just checked windows too, and its happy for me there too..
a fresh clone, `yarn` then `yarn build`

**Comment by Julusian** [comment]
Could you give it a try with the commit I just pushed?

**Comment by justingiffard** [comment]
Didn't want to fresh clone just yet and just tried `yarn` and  looks like just `yarn`ing it was all it needed. Awesome, its happy now  ¯\_(ツ)_/¯ 

Will pull your commit quick and see that it still works

**Comment by justingiffard** [comment]
Yes still happy, I'm happy to close this
