### ISSUE TITLE
Feature Request: Mute/Unmute  Variable

### ISSUE THREAD

**Issue by houtacheng** [bitfocus/companion-module-behringer-x32#65]
Would it be possible to get variables on the various states of mute or unmute?

**Comment by justingiffard** [comment]
It possible yes but would add quite a lot of variables. I can perhaps look into this though
What would you want the variables to say? "MUTED" and "UNMUTED"? or "muted" and "unmuted"?

Out of curiosity what is the use case for this? Could you not use feedbacks and change the button colour depending on if its muted or not?

**Comment by houtacheng** [comment]
I need to show "mute" or "unmute" in the button.

**Comment by istnv** [comment]
You can do that with Feedback.

**Comment by justingiffard** [comment]
Hi @houtacheng, is there a reason you can't do this with feedbacks? Why you want it to show states with text?

**Comment by Julusian** [comment]
I do this to show the mute state in the button 
![image](https://user-images.githubusercontent.com/1327476/151699226-56f19a61-10b4-4116-a12a-816c06a6eb65.png)
![image](https://user-images.githubusercontent.com/1327476/151699220-f65f1e6e-c80b-4f34-ac57-a63ce3954e5b.png)

**Comment by houtacheng** [comment]
Great!!
Maybe my module was not the latest!
