### ISSUE TITLE
Display actual fader value

### ISSUE THREAD

**Issue by ly5y** [bitfocus/companion-module-behringer-x32#69]
Perhaps this has been already discussed, nonetheless unable to find an answer.

There is a comparison available to change button presentation which uses a value retrieved form the channel or bus fader.
How the fader value itself can be displayed on the button?

Increasing and decreasing value of faders works fine, feedback showing the actual value - how?

I'm looking into the Rack version of X32 family controls where software or hardware faders are not available.

**Comment by Julusian** [comment]
You can use variables such as like this:
![image](https://user-images.githubusercontent.com/1327476/160298524-c2532805-acbf-4b6b-b44e-befbc25d6d7b.png)
Start typing `$(x32` and it will suggest available variables in the text label field.

Or have a look at the variables tab in the ui to see the full list
![image](https://user-images.githubusercontent.com/1327476/160298580-1e4d492a-be79-4cff-85de-1da8f9569f75.png)
