### ISSUE TITLE
X32/M32 Save Scene

### ISSUE THREAD

**Issue by mfullererie** [bitfocus/companion-module-behringer-x32#70]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

There is currently a feature to load a scene, but not save a scene. Would this be possible?

### Usecases

It would be nice to be able to save a scene using just one button instead of having to go through the console to do it. Especially when our X32 is a rack mount backstage.

**Comment by Tevadrum** [comment]
Hi, +1 for this function, it will be really useful !

**Comment by justingiffard** [comment]
Hi @mfullererie and @Tevadrum , I shall have a look at this, it shouldn't be too difficult (in theory) one thing I am a little worried about is people overriding things they shouldn't override. But I think that's at their own risk 
Will hopefully get a chance to look at this tomorrow and then hopefully be able to test it on Friday but if I dont manage in that time frame please dont hold it against me

**Comment by Tevadrum** [comment]
Hi Justin,
You are awesome man !
Don’t worry we won’t be angry if you don’t have it since next week.

Thanks a lot for your answer

Thomas LE NOUËN
06 46 53 69 74

**Comment by justingiffard** [comment]
Good day, I wrote the code and tested quickly tonight after our worship evening and something was going on that I need to debug and was too late to try debug tonight. Will look into this again asap though

**Comment by justingiffard** [comment]
PR just opened for this, please not it wont be accessible yet (still want to sort some stuff before making the next build) but the code is done and working

**Comment by Tevadrum** [comment]
Hi Justin,
Man you're amazing!
It's the first time I ask something on Github and your engagement is
stunning.
I will wait it patiently

Thomas

Le sam. 22 oct. 2022 à 13:21, Justin Giffard ***@***.***> a
écrit :
