### ISSUE TITLE
Feature Request: Talkback selection

### ISSUE THREAD

**Issue by saltmild** [bitfocus/companion-module-behringer-x32#78]
Would it be possiable to have the bus selection controls in the modual
Ie you can select what buses each talkback group can talk

**Comment by justingiffard** [comment]
Absolutely! I'm actually sad its not already in, adding it as we speak :)

**Comment by joelhoekstra** [comment]
Did this get implemented? I see that I can choose Talkback A or B but it would be awesome to change A or B to a chosen bus, that way we could program a way to talk to each bus individually and not only have the 2 options with A or B.

**Comment by P1TECH-CREW** [comment]
If this isn't implemented yet, does anyone know if there are OSC commands that I can throw at the M32 that would do the same thing? We could really use this command right about now!

**Comment by Sable147** [comment]
> If this isn't implemented yet, does anyone know if there are OSC commands that I can throw at the M32 that would do the same thing? 

According to [Patrick-Gilles Maillots brilliant x32 OSC documentation](https://wiki.munichmakerlab.de/images/1/17/UNOFFICIAL_X32_OSC_REMOTE_PROTOCOL_%281%29.pdf), there's a destination bitmap at `/config/talk/A/destmap`.

I've been using a set of buttons which mutes/unmutes my talkback (routed to a channel) on specific busses, so I can talk to a specific band member on their IEMs. Would be cool to implement that using the talkback channel instead of taking up a channel.

**Comment by justingiffard** [comment]
I feel like I started this last year (I mean I did say I was working on it) and never finished it but cant for the life of me remember why I stopped 🤔
I see I do have a really old branch with some code in, maybe it didnt work as expected and I couldnt get it to work as expected?I will try look at this this week so I can test it when I'm on duty next weekend

We dont need feedback on this do we'? as in have the have it change colour when talk back is on?

**Comment by Sable147** [comment]
Feedback would definitely be helpful for me to see which busses I'm currently speaking to, but it wouldn't be a dealbreaker if it isn't implemented immediately

**Comment by ldhall1856** [comment]
@justingiffard I can't wait to text this out!  When will it be available in companion? Just updated companion to 3.1.1 and don't see it in there yet.

**Comment by justingiffard-impact** [comment]
Unfortunately not in a build yet, will most likey be in a beta build first but will hopefully do that before end of week 😊 just working on something else first before I do that

**Comment by justingiffard** [comment]
Unfortunately its not in the latest stable yet, will first go to a beta
build (which you can still get) but will do that hopefully by end of this
week. Im working on adding something else too (which unfortunately is not
cooperating and I think its a bug on Beheringer side)

**Comment by ldhall1856** [comment]
Gotcha!

Thank you for working on this!  This would be a great help to my work flow at church!

**Comment by ldhall1856** [comment]
@justingiffard Any luck?

**Comment by justingiffard** [comment]
Heya, sorry for the huge delay, things got crazy at work. There's still some stuff I want to add but not sure when Im going to get to them so I think this is a good amount of enhancements for 3.1 😁 

I have requested that they build and include it in the next *beta* release (which you can download from the Bitfocus site, just beware that it is a beta release so there might be some stability issues in places )

**Comment by saltmild** [comment]
Sorry for the long delay, but just to confirm this has been working great thank you!
Currnently have repursed the the mutegroup buttons to activate triggers in companion to set the talkback states.
