### ISSUE TITLE
X32 Snippet Issue

### ISSUE THREAD

**Issue by tane650** [bitfocus/companion-module-behringer-x32#8]
Using Stream Deck through Companion - X32 will load fader setting, cues but won't load snippets. Can anyone fix this ASAP?

**Comment by Julusian** [comment]
Is this still a problem?

**Comment by tane650** [comment]
No it was solved. From memory I was using V1.3 and found a 1.4 release in a forum that solved it. Haven't used it since. Was useful though - I had the snippets recalling faders at 0dB and -10dB to mix a reality TV show to IFBs.

**Comment by Julusian** [comment]
ok great
