### ISSUE TITLE
Add variables support to action windows

### ISSUE THREAD

**Issue by antotor** [bitfocus/companion-module-behringer-x32#86]
![image](https://user-images.githubusercontent.com/5446923/222975511-c17b1eab-c38b-4d18-82e6-66591ebee8a1.png)

Hello! If this possible - please add variables support.

**Comment by justingiffard** [comment]
While this is possible, it would mean changing that number input view into a text input and adding some safety to the actions.
I'm thinking I can do this though by having a checkbox to swop out the number input for the text one so as to not lose the features that come from using a number field for a static number 🤔 

my question though, where all would you like to see this? on all the actions with "delta" in?

**Comment by justingiffard** [comment]
I added for all fader and pan deltas, let me know if threes something else you want it added to
