### ISSUE TITLE
Feature Request: Undo Cue Button

### ISSUE THREAD

**Issue by P1TECH-CREW** [bitfocus/companion-module-behringer-x32#89]
Is there a way to send a command to the M32 that initiates the undo command in the cue menu? We need to be able to load a scene and snippet combo that doesn't overwrite changes made during our shows. Snippets don't appear to be parameter safe and in testing we found that hitting undo after loading the cue we want lets us easily cycle in and out of specific scenarios. We just need a quick way to initialize this and already have a bitfocus setup.

**Comment by justingiffard** [comment]
Hi @P1TECH-CREW 
I'm looking at this issue as we speak and honestly I have never used the undo button on our X32 so not 100% sure of how it behaves

I see there are three commands related to undoing and I'm assuming that your actions will have adjusted the undo time automatically
Do you think that `/-action/doundo` will do the trick? do you think its worth while adding a `/-action/undopt` to set a checkpoint? (I see it takes in an int parameter which I have no idea what would) also do you think it would be worthwhile adding a variable for `/-undo/time`? would it be useful to you/anyone?
